project:
  title: "Palmer Penguins"
  type: datapage

website:
  navbar:
    logo: images/logo.png

format:
  datapage-html:
    theme: theme.scss

execute: 
  echo: false
  message: false
  warning: false
  error: false

redivis:
  user: datapages
  dataset: palmerpenguins
  table: penguins
